services:

  # adds top_menu_event to KevinPapst\AdminLTEBundle\Menu\MenuBuilder:
  Survos\BaseBundle\Menu\MenuBuilder:
    class: Survos\BaseBundle\Menu\MenuBuilder
    arguments:
      - "@knp_menu.factory"
      - "@event_dispatcher"
    tags:
      - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: survos_sidebar_menu }
      - { name: knp_menu.menu_builder, method: createPageMenu, alias: survos_page_menu }


# @todo: model the SurvosBase services after this.

#  KevinPapst\AdminLTEBundle\Controller\:
#    resource: '../../Controller'
#    tags: ['controller.service_arguments']
#    autowire: true
#
#  KevinPapst\AdminLTEBundle\Twig\AdminExtension:
#    class: KevinPapst\AdminLTEBundle\Twig\AdminExtension
#    arguments:
#      - '@admin_lte_theme.context_helper'
#      - '%admin_lte_theme.routes%'
#    tags:
#      - { name: twig.extension }
#
#  admin_lte_theme.context_helper:
#    class: KevinPapst\AdminLTEBundle\Helper\ContextHelper
#    alias:
#    arguments:
#      - '%admin_lte_theme.options%'
#
#  KevinPapst\AdminLTEBundle\Helper\ContextHelper:
#    alias: admin_lte_theme.context_helper
